// <auto-generated />
namespace BookClub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addingbookidtodiscussionentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingbookidtodiscussionentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202004231518033_adding bookid to discussion entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
