// <auto-generated />
namespace BookClub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addingcollectionofdiscussiontobook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingcollectionofdiscussiontobook));
        
        string IMigrationMetadata.Id
        {
            get { return "202004231412568_adding collection of discussion to book"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
