// <auto-generated />
namespace BookClub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class post_idtoPostReply : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(post_idtoPostReply));
        
        string IMigrationMetadata.Id
        {
            get { return "202005101235139_post_id to PostReply"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
